python:
  # Install our python package before building the docs, else the document will fail to build since Python and Sphinx isn't installed yet. With this change, Read the Docs will install the Python code before starting the Sphinx build, which will finish seamlessly. 
  #If you go now to the API page of your HTML documentation, you will see the home page!
  
  install:
    - method: pip
      path: .

# The following is to update the python version or to precise the version to be used. 
version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"

# The following lines is to help identify warning messages in the logs so that you can easily identify them and modify the errors. It will highlight the error messages to yellow, I think ;-)

version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"

sphinx:
  fail_on_warning: true


#The following lines is to enable PDF and EPUB downloadable versions so that the user can read the documentation offline. 
sphinx:
  fail_on_warning: true

formats:
  - pdf
  - epub
